spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ars?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 0913
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
